service : serverless-2024-prova
frameworkVersion: "3"
provider :
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  iam: 
    role: arn:aws:iam::905418207526:role/LabRole

functions: 
  hello: handler.hello
  events:
   - httpApi:
        path: /hello
        method: get
        